### ISSUE TITLE
AddPatternsFromMap panics if any of the internal pattern does not exist

### ISSUE THREAD

**Issue by logrusorgru** [vjeantet/grok#13]
Hello.

Code (reproduce):
```go
g := grok.New()
if err := g.AddPatternsFromMap(map[string]string{"SOME": `%{NOT_EXIST}`}); err != nil {
	fmt.Println(err)
}
```

Trace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gemsi/grok.sortGraph.func1(0x562070, 0x4)
	/home/username/go/src/github.com/gemsi/grok/graph.go:46 +0x58d
github.com/gemsi/grok.sortGraph(0xc82018b050, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/username/go/src/github.com/gemsi/grok/graph.go:52 +0x31d
github.com/gemsi/grok.(*Grok).AddPatternsFromMap(0xc82000e300, 0xc82018af30, 0x0, 0x0)
	/home/username/go/src/github.com/gemsi/grok/grok.go:97 +0x391
main.main()
	/home/username/grok.go:17 +0xe1
exit status 2
```

But this works fine
```go
g := grok.New()
if err := g.AddPattern("SOME", `%{NOT_EXIST}`); err != nil {
	fmt.Println(err)
}
// Output
// no pattern found for %{NOT_EXIST}
```

**Comment by logrusorgru** [comment]
Hmm, the pool-request does not solve the problem completely.
